services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: TPO
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p1234"]
      interval: 5s
      timeout: 5s
      retries: 20

  spring:
    image: ${DOCKER_USERNAME}/tpo:latest
    environment:
      JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS: 3600
      JWT_REFRESH_TOKEN_VALIDITY_IN_SECONDS: 1209600
      JWT_SECRET: ZzvFj+fF7Wj1wDg7g0oF7VgZ/6jJ2c+uqwDSFDAGefawwe2gewg24
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
